[versions]
agp = "8.4.0"
kotlin = "1.9.0"
appcompat = "1.7.0"
material = "1.12.0"
attribution = "2.4.9"
appsFlyer = "6.12.2"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
attribution = { group = "dev.deeplink.sdk", name = "attribution", version.ref = "attribution" }
appsflyer = { group = "com.appsflyer", name = "af-android-sdk", version.ref = "appsFlyer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
